/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelo.Cuenta;

/**
 *
 * @author daw1
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form MiVentana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorFicheros = new javax.swing.JFileChooser();
        Cuenta = new javax.swing.JPanel();
        codigo = new javax.swing.JLabel();
        titular = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        tCodigo = new javax.swing.JTextField();
        tTitular = new javax.swing.JTextField();
        tSaldo = new javax.swing.JTextField();
        ListCuentas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCuentas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MiArchivo = new javax.swing.JMenu();
        MiAbrir = new javax.swing.JMenuItem();
        MiGuardar = new javax.swing.JMenuItem();
        MiBanco = new javax.swing.JMenu();
        abrirCuenta = new javax.swing.JMenuItem();
        operar = new javax.swing.JMenuItem();
        cancelarCuenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cuenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));
        Cuenta.setToolTipText("");
        Cuenta.setName("Cuenta"); // NOI18N

        codigo.setText("CODIGO");

        titular.setText("TITULAR");

        saldo.setText("SALDO");

        tSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuentaLayout = new javax.swing.GroupLayout(Cuenta);
        Cuenta.setLayout(CuentaLayout);
        CuentaLayout.setHorizontalGroup(
            CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuentaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuentaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        CuentaLayout.setVerticalGroup(
            CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuentaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo)
                    .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titular)
                    .addComponent(tTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldo)
                    .addComponent(tSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        ListCuentas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Cuentas"));

        cuentaTM=new CuentaTableModel();
        tablaCuentas.setModel(cuentaTM);
        tablaCuentas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaCuentas);
        tablaCuentas.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent lse){
                int fila=tablaCuentas.getSelectedRow();
                if(fila>=0){
                    tCodigo.setText((String)tablaCuentas.getValueAt(fila,0));
                    tTitular.setText((String)tablaCuentas.getValueAt(fila,1));
                    tSaldo.setText(tablaCuentas.getValueAt(fila,2).toString());
                }
            }
        });

        javax.swing.GroupLayout ListCuentasLayout = new javax.swing.GroupLayout(ListCuentas);
        ListCuentas.setLayout(ListCuentasLayout);
        ListCuentasLayout.setHorizontalGroup(
            ListCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(ListCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListCuentasLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ListCuentasLayout.setVerticalGroup(
            ListCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
            .addGroup(ListCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListCuentasLayout.createSequentialGroup()
                    .addContainerGap(13, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 204));

        MiArchivo.setBackground(new java.awt.Color(102, 255, 204));
        MiArchivo.setText("Archivo");
        MiArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiArchivoActionPerformed(evt);
            }
        });

        MiAbrir.setText("Abrir");
        MiAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiAbrirActionPerformed(evt);
            }
        });
        MiArchivo.add(MiAbrir);

        MiGuardar.setText("Guardar");
        MiGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiGuardarActionPerformed(evt);
            }
        });
        MiArchivo.add(MiGuardar);

        jMenuBar1.add(MiArchivo);

        MiBanco.setBackground(new java.awt.Color(102, 255, 204));
        MiBanco.setText("Banco");

        abrirCuenta.setText("Abrir Cuenta");
        abrirCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCuentaActionPerformed(evt);
            }
        });
        MiBanco.add(abrirCuenta);

        operar.setText("Operar con Cuenta");
        operar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operarActionPerformed(evt);
            }
        });
        MiBanco.add(operar);

        cancelarCuenta.setText("Cancelar Cuenta");
        MiBanco.add(cancelarCuenta);

        jMenuBar1.add(MiBanco);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Cuenta.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiGuardarActionPerformed
       if(selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            int SAVE_DIALOG = JFileChooser.SAVE_DIALOG;
        } 
    }//GEN-LAST:event_MiGuardarActionPerformed

    private void tSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSaldoActionPerformed

    private void MiArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiArchivoActionPerformed

    private void MiAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiAbrirActionPerformed
       if(selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            int OPEN_DIALOG=JFileChooser.OPEN_DIALOG;
        }
    }//GEN-LAST:event_MiAbrirActionPerformed

    private void abrirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCuentaActionPerformed
     if(this.dialogo.mostrar()==DialogoCuenta.ACEPTAR){
        this.tCodigo.setText(dialogo.getCodigo());
        this.tTitular.setText(dialogo.getTitular());
        this.tSaldo.setText(Float.toString(dialogo.getSaldo()));
        controlador.abrirCuenta();
     }
    }//GEN-LAST:event_abrirCuentaActionPerformed

    private void operarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    private Controlador controlador;
    //metodo que permite fijar el controlador
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    public void mostrar(){
    setVisible(true);
    }
    public String getCodigo(){
    return this.tCodigo.getText();
    }
    public String getTitular(){
    return this.tTitular.getText();
    }
    public float getSaldo(){
    return  Float.parseFloat(this.tSaldo.getText());
    }
    public String getOperacion(){
    int op;
    String salida;
        op = JOptionPane.showOptionDialog(this,"Operacion a realizar","Operar con cuenta",WIDTH,HEIGHT,null,new String[]{"INGRESAR","REINTEGRAR"},"XX");
    switch(op){
        case 1: salida="INGRESO";
        break;
        case 2: salida="REINTEGRO";
        break;
        default: salida=null;
    }return salida;
    }
    public float getCantidad(){
    String entrada=JOptionPane.showInputDialog(this,"Introduzca cantidad");
    if(entrada!=null){
    try{
    return Float.parseFloat(entrada);
    }catch(NumberFormatException nfe){
        mostrarMensaje("Error en la cantidad");
    }
    }
    return -1;
    }
    public void mostrarCuentas(List<Cuenta> listado){
        cuentaTM.setCuentas(listado);
    }
   
    public String getArchivo(){
    return null;
    }
    public void actualizarTabla(){
    
    }
    public void mostrarMensaje(String mensaje){
            JOptionPane.showMessageDialog(this,mensaje);}
    private DialogoCuenta dialogo=new DialogoCuenta(this,true);
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuenta;
    private javax.swing.JPanel ListCuentas;
    private javax.swing.JMenuItem MiAbrir;
    private javax.swing.JMenu MiArchivo;
    private javax.swing.JMenu MiBanco;
    private javax.swing.JMenuItem MiGuardar;
    private javax.swing.JMenuItem abrirCuenta;
    private javax.swing.JMenuItem cancelarCuenta;
    private javax.swing.JLabel codigo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem operar;
    private javax.swing.JLabel saldo;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTextField tSaldo;
    private javax.swing.JTextField tTitular;
    private CuentaTableModel cuentaTM;
    private javax.swing.JTable tablaCuentas;
    private javax.swing.JLabel titular;
    // End of variables declaration//GEN-END:variables
}
